### Activity 1.2 {-}
Researchers at a maternity hospital in the 1970s conducted a study of low birth weight babies. Low birth weight is classified as a weight of 2500g or less at birth. Data were collected on age and smoking status of mothers and the birth weight of their babies. The file `Activity_S1.2.rds` contain data on the participants in the study. The file is located on Moodle in the Learning Activities section.

Create a 2 by 2 table to show the proportions of low birth weight babies born to mothers who smoked during pregnancy and those that did not smoke during pregnancy. Answer the following questions:

a) What was the total number of mothers who smoked during pregnancy?
b) What proportion of mothers who smoked gave birth to low birth weight babies? What proportion of non-smoking mothers gave birth to low birth weight babies?
c) Construct a stacked bar chart of the data to examine if there a difference in the proportion of babies born with a low birth weight in relation to the age group of the mother? Provide appropriate labels for the axes and give the graph an appropriate title. [Hint: plot the data using the `AgeGrp` variable]
d) Using your answers to the question a) and b), write a brief conclusion about the relationship of low birth weight and mother’s age and smoking status.

### Activity 2.1 {-}

In a Randomised Controlled Trial, the preference of a new drug was tested against an established drug by giving both drugs to each of 90 people. Assume that the two drugs are equally preferred, that is, the probability that a patient prefers either of the drugs is equal (50%). Use one of the binomial functions in Stata or R to compute the probability that 60 or more patients would prefer the new drug. In completing this question, determine:

a)	The number of trials (`n` for Stata, `size` for R)
b)	The number of successes we are interested in (`k` for Stata, `x` or `q` for R)
c)	The probability of success for each trial (`p` for Stata, `prob` for R)
d)	The form of the binomial function
    - for Stata: `binomialp`, `binomial` or `binomialtail`;
    - for R: `dbinom`, `pbinom` or `pbinom(lower.tail=FALSE)`
e)	The final probability.

### Activity 2.2 {-}

A case of Schistosomiasis is identified by the detection of schistosome ova in a faecal sample. In patients with a low level of infection, a field technique of faecal examination has a probability of 0.35 of detecting ova in any one faecal sample. If five samples are routinely examined for each patient, use Stata or R to compute the probability that a patient with a low level of infection:

a)	Will not be identified?
b)	Will be identified in two of the samples?
c)	Will be identified in all the samples?
d)	Will be identified in at most 3 of the samples?

### Activity 2.3 {-}

If weights of men are Normally distributed with a population mean $\mu$ = 87, and a population standard deviation, $\sigma$ = 8 kg:

a)	What is the probability that a man will weigh 95 kg or more?  Draw a Normal curve of the area represented by this probability in the population (i.e. with $\mu$ = 87 kg and $\sigma$ = 8 kg).
b)	What is the probability that a man will weigh more than 75 kg but less than 95 kg?  Draw the area represented by this probability on a Normal curve.

### Activity 2.4 {-}

Using the health survey data (`Activity_S2.4.xlsx`) described in the computing notes of this module, create a new variable, BMI, which is equal to a person's weight (in kg) divided by their height (in metres) squared (i.e. $\text{BMI} = \frac{\text{weight (kg)}}{\text{[height (m)]}^2}$. Categorise BMI using the categories:

-   Underweight: BMI \< 18.5
-   Normal weight: 18.5 $\le$ BMI \< 25
-   Overweight: 25 $\le$ BMI \< 30
-   Obese: BMI $\ge$ 30

Note: BMI does not necessarily reflect body fat distribution or describe the same degree of fatness in different individuals. However, at a population level, BMI is a practical and useful measure for identifying overweight or obesity. [^BMI]

[^BMI]: https://www.aihw.gov.au/reports/overweight-obesity/overweight-and-obesity/contents/measuring-overweight-and-obesity

Create a two-way table to display the distribution of BMI categories by sex (sex: 1 = respondent identifies as male; 2 = respondent identifies as female). Does there appear to be a difference in categorised BMI between males and females?

### Activity 2.5 {-}

The data in the files `Activity_S2.5.dta` and `Activity_S2.5.rds` (available on Moodle) has information about **birth weight** and **length of stay** collected from 117 babies admitted consecutively to a hospital for surgery. For each variable:

a.  Create a histogram to inspect the distribution of the variable;

b.  Complete the following summary statistics for each variable:
    - mean and median;
    - standard deviation and interquartile range.

Make a decision about whether each variable is symmetric or not, and which measure of central tendency and variability should be reported.

### Activity 2.6 {-}
The data set of hospital stay data for 1323 hypothetical patients is available on Moodle in csv format (`Activity2.6.csv`). Import this dataset into Stata or R. There are two variables in this dataset:

- female: female=1; male=0
- los: length of stay in days

a)	Use Stata or R to examine the distribution of length of stay: overall; and separately for females and males. Comment on the distributions.
b)	Use Stata or R to calculate measures of central tendency for hospital stay to obtain information about the average duration of hospital stay. Which summary statistics should you report and why? Report the appropriate statistics of the spread and measure of central tendency chosen.
c)	Calculate the measures of central tendency for hospital duration separately for males and females. What can you conclude from comparing these measures for males and females? 
