project:
  type: book
  output-dir: docs

book:
  title: "PHCM9795: Foundations of Biostatistics"
  author: "Timothy Dobbins"
  date: "13-Jun-2024"
  date-format: "DD MMMM, YYYY"
  version: 1.2
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-probability.qmd
    - 03-precision.qmd
    - 04-hypothesis-testing.qmd
    - 05-comparing-two-means.qmd
    - 06-proportions.qmd
    - 07-testing-proportions.qmd
    - 08-correlation-and-regression.qmd
    - 09-non-parametrics.qmd
    - 10-sample-size.qmd
    # - 98.1-appendix1.qmd
    - references.qmd
    
    ####################
    # Where to put deleting a record???
    # Was in Module 5, move earlier
    #
    # Mod 5 - include t-test for summarised data?
    ####################

bibliography: PHCM9795.bib

pdf-engine: xelatex

format:
  html:
    theme: cosmo
    highlight-style: monochrome
    title-block-banner: "#ffdc00"
  pdf:
    papersize: A4
    documentclass: memoir
    mainfont: Roboto
    sansfont: Clancy
    include-in-header: preamble.tex
    highlight-style: monochrome
    keep-md: true
