<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Comparing the means of two groups – PHCM9795: Foundations of Biostatistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06-proportions.html" rel="next">
<link href="./04-hypothesis-testing.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-29fdfc89ac7fc112ecf2c1fbf9d5ebfc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9a71a2450f5674972ff858c43d8deec0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: #ffdc00;
      }
</style>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-comparing-two-means.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PHCM9795: Foundations of Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to biostatistics and data fundamentals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical data, presentation guidelines and probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-precision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Continuous probability distributions, sampling and precision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">An introduction to hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comparing-two-means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-testing-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-correlation-and-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-non-parametrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98.1-appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#optional-readings" id="toc-optional-readings" class="nav-link" data-scroll-target="#optional-readings">Optional readings</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">5.1</span> Introduction</a></li>
  <li><a href="#independent-samples-t-test" id="toc-independent-samples-t-test" class="nav-link" data-scroll-target="#independent-samples-t-test"><span class="header-section-number">5.2</span> Independent samples t-test</a>
  <ul class="collapse">
  <li><a href="#assumptions-for-an-independent-samples-t-test" id="toc-assumptions-for-an-independent-samples-t-test" class="nav-link" data-scroll-target="#assumptions-for-an-independent-samples-t-test"><span class="header-section-number">5.2.1</span> Assumptions for an independent samples t-test</a></li>
  <li><a href="#worked-example-5.1" id="toc-worked-example-5.1" class="nav-link" data-scroll-target="#worked-example-5.1"><span class="header-section-number">5.2.2</span> Worked Example 5.1</a></li>
  <li><a href="#conducting-and-interpreting-an-independent-samples-t-test" id="toc-conducting-and-interpreting-an-independent-samples-t-test" class="nav-link" data-scroll-target="#conducting-and-interpreting-an-independent-samples-t-test"><span class="header-section-number">5.2.3</span> Conducting and interpreting an independent samples t-test</a></li>
  </ul></li>
  <li><a href="#paired-t-tests" id="toc-paired-t-tests" class="nav-link" data-scroll-target="#paired-t-tests"><span class="header-section-number">5.3</span> Paired t-tests</a>
  <ul class="collapse">
  <li><a href="#assumptions-for-a-paired-t-test" id="toc-assumptions-for-a-paired-t-test" class="nav-link" data-scroll-target="#assumptions-for-a-paired-t-test"><span class="header-section-number">5.3.1</span> Assumptions for a paired t-test</a></li>
  <li><a href="#computing-a-paired-t-test" id="toc-computing-a-paired-t-test" class="nav-link" data-scroll-target="#computing-a-paired-t-test"><span class="header-section-number">5.3.2</span> Computing a paired t-test</a></li>
  <li><a href="#worked-example-5.2" id="toc-worked-example-5.2" class="nav-link" data-scroll-target="#worked-example-5.2"><span class="header-section-number">5.3.3</span> Worked Example 5.2</a></li>
  </ul></li>
  <li><a href="#jamovi-notes" id="toc-jamovi-notes" class="nav-link" data-scroll-target="#jamovi-notes">Jamovi notes</a>
  <ul class="collapse">
  <li><a href="#checking-data-for-the-independent-samples-t-test" id="toc-checking-data-for-the-independent-samples-t-test" class="nav-link" data-scroll-target="#checking-data-for-the-independent-samples-t-test"><span class="header-section-number">5.4</span> Checking data for the independent samples t-test</a>
  <ul class="collapse">
  <li><a href="#examining-variable-distributions-by-a-second-variable" id="toc-examining-variable-distributions-by-a-second-variable" class="nav-link" data-scroll-target="#examining-variable-distributions-by-a-second-variable"><span class="header-section-number">5.4.1</span> Examining variable distributions by a second variable</a></li>
  </ul></li>
  <li><a href="#independent-samples-t-test-1" id="toc-independent-samples-t-test-1" class="nav-link" data-scroll-target="#independent-samples-t-test-1"><span class="header-section-number">5.5</span> Independent samples t-test</a></li>
  <li><a href="#checking-the-assumptions-for-a-paired-t-test" id="toc-checking-the-assumptions-for-a-paired-t-test" class="nav-link" data-scroll-target="#checking-the-assumptions-for-a-paired-t-test"><span class="header-section-number">5.6</span> Checking the assumptions for a Paired t-test</a></li>
  <li><a href="#paired-t-test" id="toc-paired-t-test" class="nav-link" data-scroll-target="#paired-t-test"><span class="header-section-number">5.7</span> Paired t-Test</a></li>
  </ul></li>
  <li><a href="#r-notes" id="toc-r-notes" class="nav-link" data-scroll-target="#r-notes">R notes</a>
  <ul class="collapse">
  <li><a href="#checking-data-for-the-independent-samples-t-test-1" id="toc-checking-data-for-the-independent-samples-t-test-1" class="nav-link" data-scroll-target="#checking-data-for-the-independent-samples-t-test-1"><span class="header-section-number">5.8</span> Checking data for the independent samples t-test</a>
  <ul class="collapse">
  <li><a href="#examining-variable-distributions-by-a-second-variable-1" id="toc-examining-variable-distributions-by-a-second-variable-1" class="nav-link" data-scroll-target="#examining-variable-distributions-by-a-second-variable-1"><span class="header-section-number">5.8.1</span> Examining variable distributions by a second variable</a></li>
  </ul></li>
  <li><a href="#independent-samples-t-test-2" id="toc-independent-samples-t-test-2" class="nav-link" data-scroll-target="#independent-samples-t-test-2"><span class="header-section-number">5.9</span> Independent samples t-test</a></li>
  <li><a href="#checking-the-assumptions-for-a-paired-t-test-1" id="toc-checking-the-assumptions-for-a-paired-t-test-1" class="nav-link" data-scroll-target="#checking-the-assumptions-for-a-paired-t-test-1"><span class="header-section-number">5.10</span> Checking the assumptions for a Paired t-test</a></li>
  <li><a href="#paired-t-test-1" id="toc-paired-t-test-1" class="nav-link" data-scroll-target="#paired-t-test-1"><span class="header-section-number">5.11</span> Paired t-Test</a></li>
  </ul></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a>
  <ul class="collapse">
  <li><a href="#activity-5.1" id="toc-activity-5.1" class="nav-link" data-scroll-target="#activity-5.1">Activity 5.1</a></li>
  <li><a href="#activity-5.2" id="toc-activity-5.2" class="nav-link" data-scroll-target="#activity-5.2">Activity 5.2</a></li>
  <li><a href="#activity-5.3" id="toc-activity-5.3" class="nav-link" data-scroll-target="#activity-5.3">Activity 5.3</a></li>
  <li><a href="#activity-5.4" id="toc-activity-5.4" class="nav-link" data-scroll-target="#activity-5.4">Activity 5.4</a></li>
  <li><a href="#supplementary-activity-5.5" id="toc-supplementary-activity-5.5" class="nav-link" data-scroll-target="#supplementary-activity-5.5">Supplementary Activity 5.5</a></li>
  <li><a href="#activity-5.6" id="toc-activity-5.6" class="nav-link" data-scroll-target="#activity-5.6"><span class="header-section-number">5.11.1</span> Activity 5.6</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>By the end of this module you will be able to:</p>
<ul>
<li>Decide whether to use an independent samples t-test or a paired t-test to compare two the means of two groups;</li>
<li>Conduct and interpret the results from an independent samples t-test;</li>
<li>Describe the assumptions of an independent samples t-test;</li>
<li>Conduct and interpret the results from a paired t-test;</li>
<li>Describe the assumptions of a paired t-test;</li>
<li>Conduct an independent samples t-test and a paired t-test using software;</li>
<li>Report results and provide a concise summary of the findings of statistical analyses.</li>
</ul>
</section>
<section id="optional-readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="optional-readings">Optional readings</h2>
<p><span class="citation" data-cites="kirkwood_sterne01">Kirkwood and Sterne (<a href="references.html#ref-kirkwood_sterne01" role="doc-biblioref">2001</a>)</span>; Sections 7.1 to 7.5. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728">[UNSW Library Link]</a></p>
<p><span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>; Section 10.3. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730">[UNSW Library Link]</a></p>
</section>
<section id="introduction" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">5.1</span> Introduction</h2>
<p>In Module 4, a one-sample t-test was used for comparing a single mean to a hypothesised value. In health research, we often want to compare the means between two groups. For example, in an observational study, we may want to compare cholesterol levels in people who exercise regularly to the levels in people who do not exercise regularly. In a clinical trial, we may want to compare cholesterol levels in people who have been randomised to a dietary modification or to usual care. In this module, we show how to compare the means of two groups where the analysis variable is normally distributed.</p>
<p>From the decision tree presented in the Appendix, we can see that if we have a continuous outcome measure and two categorical groups that are not related, i.e.&nbsp;a binary exposure measurement, the test for such data is an independent samples t-test. The test is also sometimes called a 2-sample t-test.</p>
<p>In research, data are often ‘paired’ or ‘matched’, that is the two data points are related to one another. This occurs when measurements are taken:</p>
<ul>
<li>From each participant on two occasions, e.g.&nbsp;at baseline and follow-up in an experimental study or in a longitudinal cohort study;</li>
<li>From related people, e.g.&nbsp;a mother and daughter or a child and their sibling;</li>
<li>From related sites in the same person, e.g.&nbsp;from both limbs, eyes or kidneys;</li>
<li>From matched participants e.g.&nbsp;in a matched case-control study;</li>
<li>In cross-over clinical trials where the patient receives both drugs, often in random order.</li>
</ul>
<p>An independent samples t-test cannot be used for analysing paired or matched data because the assumption that the two groups are independent is violated. Treating paired or matched measurements as independent samples would artificially inflate the sample size and lead to inaccurate P values. When the data are related in a paired or matched way and the outcome is continuous, a paired t-test is the appropriate statistic to use if the data are normally distributed.</p>
</section>
<section id="independent-samples-t-test" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="independent-samples-t-test"><span class="header-section-number">5.2</span> Independent samples t-test</h2>
<p>An independent samples t-test is a parametric test that is used to assess whether the mean values of two groups are different from one another. Thus, the test is used to assess whether two mean values are similar enough to have come from the same population or whether the difference between them is so large that the two groups can be considered to have come from separate populations with different characteristics.</p>
<p>The null hypothesis is that the mean values of the two groups are not different, that is:</p>
<p>H<sub>0</sub>: (<span class="math inline">\(\mu_1 - \mu_2\)</span>) = 0</p>
<p>Rejecting the null hypothesis using an independent samples t-test indicates that the difference between the means of the two groups is large in relation to the variability in the samples and is unlikely to be due to chance or to sampling variation.</p>
<section id="assumptions-for-an-independent-samples-t-test" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="assumptions-for-an-independent-samples-t-test"><span class="header-section-number">5.2.1</span> Assumptions for an independent samples t-test</h3>
<p>The assumptions that must be met before an independent samples t-test can be used are:</p>
<ul>
<li>The two groups are independent</li>
<li>The measurements are independent</li>
<li>The analysis variable must be continuous and must be normally distributed in each group</li>
</ul>
<p>The first two assumptions are determined by the study design. The two samples must be independent, i.e.&nbsp;if a person is in one group then they cannot be included in the other group, and the measurements within a sample must be independent, i.e.&nbsp;each person must be included in their group once only.</p>
<p>The third assumption of normality is important although t-tests are robust to some degree of non-normality as long as there are no influential outliers and, more importantly, if the sample size is large. We examined how to assess normality in Module 2. If the data are not normally distributed, it may be possible to transform them using a mathematical function such as a logarithmic transformation. If not, then we may need to use non-parametric tests. This is examined in Module 9.</p>
<p>Traditionally, the variance of the analysis variable in each group was assumed to be equal. However, this assumption can be relaxed by using Welch’s variation of the t-test. It has been recommended that this unequal-variances t-test be used in most, if not all situations <span class="citation" data-cites="west21 delacre_etal17 ruxton06">(<a href="references.html#ref-west21" role="doc-biblioref">West 2021</a>; <a href="references.html#ref-delacre_etal17" role="doc-biblioref">Delacre, Lakens, and Leys 2017</a>; <a href="references.html#ref-ruxton06" role="doc-biblioref">Ruxton 2006</a>)</span>.</p>
</section>
<section id="worked-example-5.1" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="worked-example-5.1"><span class="header-section-number">5.2.2</span> Worked Example 5.1</h3>
<p>In an observational study of a random sample of 100 full term babies from the community, birth weight and gender were measured. There were 44 male babies and 56 female babies in the sample. The research question asked whether there was a difference in birth weights between boys and girls. The two groups are independent of each other and therefore an independent samples t-test can be used to test the null hypothesis that there is no difference in weight between the genders.</p>
<p>Exploratory data analysis of the variable of interest in each group should always be obtained before a t-test is undertaken to ensure that the assumptions are met. In particular, the distribution of the analysis variable should be examined for each group, as shown in <a href="#fig-mod05-bwt-gender" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>. The <code>mod05_birthweight.rds</code> dataset is available on Moodle.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod05-bwt-gender" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mod05-bwt-gender-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/mod05/mod05-bwt-gender.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mod05-bwt-gender-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.1: Distribution of birth weight by gender
</figcaption>
</figure>
</div>
</div>
</div>
<p>The plots show that the data are approximately normally distributed: the density curves are relatively bell shaped and symmetric, and there are no outliers.</p>
<p>We can also describe the data using summary statistics:</p>
<div class="cell">
<div id="tbl-5-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-5-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1: Summary of birthweight by gender
</figcaption>
<div aria-describedby="tbl-5-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-65e15bf2{}.cl-65d8d4aa{font-family:'Helvetica';font-size:11pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-65d8d4be{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-65d9fad8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65d9fad9{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:2pt;padding-top:2pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65d9fada{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65d9fae2{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65d9fae3{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:15pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65da0794{width:1.608in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65da0795{width:1.406in;background-color:transparent;vertical-align: middle;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 1pt solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65da0796{width:1.608in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65da079e{width:1.406in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65da079f{width:1.608in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65da07a0{width:1.406in;background-color:transparent;vertical-align: top;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65da07a1{width:1.608in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65da07a2{width:1.406in;background-color:transparent;vertical-align: top;border-bottom: 1pt solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-65e15bf2"><thead><tr style="overflow-wrap:break-word;"><th class="cl-65da0794"><p class="cl-65d9fad8"><span class="cl-65d8d4aa">Characteristic</span></p></th><th class="cl-65da0795"><p class="cl-65d9fad9"><span class="cl-65d8d4aa">Female</span></p></th><th class="cl-65da0795"><p class="cl-65d9fad9"><span class="cl-65d8d4aa">Male</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-65da0796"><p class="cl-65d9fada"><span class="cl-65d8d4be">Birthweight</span></p></td><td class="cl-65da079e"><p class="cl-65d9fae2"><span class="cl-65d8d4be"></span></p></td><td class="cl-65da079e"><p class="cl-65d9fae2"><span class="cl-65d8d4be"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65da079f"><p class="cl-65d9fae3"><span class="cl-65d8d4be">Number</span></p></td><td class="cl-65da07a0"><p class="cl-65d9fae2"><span class="cl-65d8d4be">56</span></p></td><td class="cl-65da07a0"><p class="cl-65d9fae2"><span class="cl-65d8d4be">44</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65da0796"><p class="cl-65d9fae3"><span class="cl-65d8d4be">Mean (SD)</span></p></td><td class="cl-65da079e"><p class="cl-65d9fae2"><span class="cl-65d8d4be">3.59 (0.36)</span></p></td><td class="cl-65da079e"><p class="cl-65d9fae2"><span class="cl-65d8d4be">3.42 (0.35)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65da0796"><p class="cl-65d9fae3"><span class="cl-65d8d4be">Median (Q1, Q3)</span></p></td><td class="cl-65da079e"><p class="cl-65d9fae2"><span class="cl-65d8d4be">3.53 (3.32, 3.88)</span></p></td><td class="cl-65da079e"><p class="cl-65d9fae2"><span class="cl-65d8d4be">3.43 (3.15, 3.63)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65da07a1"><p class="cl-65d9fae3"><span class="cl-65d8d4be">Range</span></p></td><td class="cl-65da07a2"><p class="cl-65d9fae2"><span class="cl-65d8d4be">2.95 to 4.25</span></p></td><td class="cl-65da07a2"><p class="cl-65d9fae2"><span class="cl-65d8d4be">2.75 to 4.10</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>The table shows that girls have a mean weight of 3.59 kg (SD 0.36) and boys have a mean weight of 3.42 kg (SD 0.35) with females being heavier than males. The variabilities of birth weight (i.e.&nbsp;the standard deviation) are similar between the two groups.</p>
</section>
<section id="conducting-and-interpreting-an-independent-samples-t-test" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="conducting-and-interpreting-an-independent-samples-t-test"><span class="header-section-number">5.2.3</span> Conducting and interpreting an independent samples t-test</h3>
<p>An independent samples t-test provides us with a t statistic from which we can compute a P value. The computation of the t statistic is as follows:</p>
<p><span class="math display">\[t = \frac{{\overline{x}}_{1} - {\overline{x}}_{2}}{SE({\overline{x}}_{1} - {\overline{x}}_{2})}\]</span></p>
<p>with the standard error and degrees of freedom calculated from software. Note that by using Welch’s t-test, the degrees of freedom will usually not be a whole number, and will appear with decimals.</p>
<p>Looking at the formula for the t-statistic, we can see that the <span class="math inline">\(t\)</span> is an estimate of how different the mean values are compared to the variability of the difference in means. So <span class="math inline">\(t\)</span> will become larger as the difference in means increases with respect to the variability.</p>
<p>Statistical software will calculate both the t and P values. If the t-value is large, the P value will be small, providing evidence against the null hypothesis of no difference between the groups.</p>
<p><a href="#tbl-ind-t" class="quarto-xref">Table&nbsp;<span>5.2</span></a> summarises the results of an independent samples t-test using <code>mod05_birthweight.dta</code> or <code>mod05_birthweight.rds</code>. The process of conducting the t-test is summarised for jamovi and R in the following sections.</p>
<div class="cell">
<div id="tbl-ind-t" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ind-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.2: Birthweight (kg) by sex
</figcaption>
<div aria-describedby="tbl-ind-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-65f101a6{}.cl-65ec9440{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-65edc270{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65edc27a{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65edce46{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce50{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce51{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce5a{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce5b{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce5c{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce5d{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce5e{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65edce64{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-65f101a6"><thead><tr style="overflow-wrap:break-word;"><th class="cl-65edce46"><p class="cl-65edc270"><span class="cl-65ec9440">Sex</span></p></th><th class="cl-65edce50"><p class="cl-65edc27a"><span class="cl-65ec9440">n</span></p></th><th class="cl-65edce51"><p class="cl-65edc270"><span class="cl-65ec9440">Mean (SE)</span></p></th><th class="cl-65edce51"><p class="cl-65edc270"><span class="cl-65ec9440">95% Confidence Interval</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-65edce5a"><p class="cl-65edc270"><span class="cl-65ec9440">Female</span></p></td><td class="cl-65edce5b"><p class="cl-65edc27a"><span class="cl-65ec9440">56</span></p></td><td class="cl-65edce5c"><p class="cl-65edc270"><span class="cl-65ec9440">3.59 (0.049)</span></p></td><td class="cl-65edce5c"><p class="cl-65edc270"><span class="cl-65ec9440">3.49 to 3.68</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65edce5a"><p class="cl-65edc270"><span class="cl-65ec9440">Male</span></p></td><td class="cl-65edce5b"><p class="cl-65edc27a"><span class="cl-65ec9440">44</span></p></td><td class="cl-65edce5c"><p class="cl-65edc270"><span class="cl-65ec9440">3.42 (0.053)</span></p></td><td class="cl-65edce5c"><p class="cl-65edc270"><span class="cl-65ec9440">3.31 to 3.53</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65edce5d"><p class="cl-65edc270"><span class="cl-65ec9440">Difference</span></p></td><td class="cl-65edce5e"><p class="cl-65edc27a"><span class="cl-65ec9440"></span></p></td><td class="cl-65edce64"><p class="cl-65edc270"><span class="cl-65ec9440">0.17 (0.072)</span></p></td><td class="cl-65edce64"><p class="cl-65edc270"><span class="cl-65ec9440">0.02 to 0.31</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>Here we see that girls are heavier than boys, and the mean difference in weights between the genders is 0.17 kg (95% CI 0.02, 0.31). We are 95% confident that the true mean difference of weight between girls and boys lies between 0.02 and 0.31 kg. Note that this interval does not contain the null value of 0.</p>
<p>Here we are testing the null hypothesis of no difference in mean birthweights between females and males: a two-sided test. The t-value is calculated as 2.30 with 93.5 degrees of freedom, and yields a two-sided P value of 0.023, providing evidence of a difference in mean birthweight between sex.</p>
</section>
</section>
<section id="paired-t-tests" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="paired-t-tests"><span class="header-section-number">5.3</span> Paired t-tests</h2>
<p>If the outcome of interest is the difference in the continuously outcome measurement between each pair of observations, a paired t-test is used. In effect, a paired t-test is used to assess whether the mean of the differences between the two related measurements is significantly different from zero. In this sense, a paired t-test is very closely aligned with a one sample t-test.</p>
<p>When using a paired t-test, the variation <em>between the pairs</em> of measurements is the most important statistic. The variation between the participants is of little interest.</p>
<p>For related measurements, the data for each pair of values must be entered on the same row of the spreadsheet. Thus, the number of rows in the data sheet is the number of pairs of observations. Thus, the effective sample size is the total number of pairs and not the total number of measurements.</p>
<section id="assumptions-for-a-paired-t-test" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="assumptions-for-a-paired-t-test"><span class="header-section-number">5.3.1</span> Assumptions for a paired t-test</h3>
<p>The assumptions for a paired t-test are:</p>
<ul>
<li>the outcome variable is continuous</li>
<li>the differences between the pair of the measurements are normally distributed</li>
</ul>
<p>For a paired samples t-test, it is important to test whether the <em>differences</em> between the two measurements are normally distributed. If the assumptions for a paired t-test cannot be met, a non-parametric equivalent is a more appropriate test to use (Module 9).</p>
</section>
<section id="computing-a-paired-t-test" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="computing-a-paired-t-test"><span class="header-section-number">5.3.2</span> Computing a paired t-test</h3>
<p>The null hypothesis for using a paired t-test is as follows:</p>
<p>H<sub>0</sub>: Mean (Measurement1 – Measurement2) = 0</p>
<p>To compute a t-value, the size of the mean difference between the two measurements is compared to the standard error of the paired differences, i.e.</p>
<p><span class="math display">\[t = \frac{\overline{d}}{SE(\overline{d})}\]</span></p>
<p>with <em>n</em>–1 degrees of freedom, where <em>n</em> is the number of pairs.</p>
<p>Because the standard error becomes smaller as the sample size becomes larger, the t-value increases as the sample size increases for the same mean difference.</p>
</section>
<section id="worked-example-5.2" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="worked-example-5.2"><span class="header-section-number">5.3.3</span> Worked Example 5.2</h3>
<p>A total of 107 people were recruited into a study to assess whether ankle blood pressure measured in two different sites would be the same. For each person, systolic blood pressure (SBP) was measured in two sites: dorsalis pedis and tibialis posterior.</p>
<p>The dataset mod05_ankle_bp.xls is available on Moodle. First, we need to compute the pairwise difference between SBP measured in the two sites. The distribution of the difference between SBP measured in dorsalis pedis and tibialis posterior is shown in <a href="#fig-mod05-sbpdiff" class="quarto-xref">Figure&nbsp;<span>5.2</span></a>. The differences approximate a normal distribution and therefore a paired t-test can be used.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod05-sbpdiff" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mod05-sbpdiff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/mod05/mod05-sbpdiff.png" class="img-fluid figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mod05-sbpdiff-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5.2: Distribution of differences in ankle SBP between two sites of 107 participants
</figcaption>
</figure>
</div>
</div>
</div>
<p>The paired t-test can be performed using statistical software, with a summary of the results presented in <a href="#tbl-paired-t" class="quarto-xref">Table&nbsp;<span>5.3</span></a>. We can see that the mean SBP is very similar in the two sites.</p>
<div class="cell">
<div id="tbl-paired-t" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-paired-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.3: Systolic blood pressure (mmHg) measured at two sites on the ankle
</figcaption>
<div aria-describedby="tbl-paired-t-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-65fde39e{}.cl-65fb4102{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-65fc51b4{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65fc51be{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-65fc5d12{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d1c{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d1d{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d26{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d27{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d28{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d30{width:1.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d31{width:0.5in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-65fc5d32{width:1in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-65fde39e"><thead><tr style="overflow-wrap:break-word;"><th class="cl-65fc5d12"><p class="cl-65fc51b4"><span class="cl-65fb4102">Site</span></p></th><th class="cl-65fc5d1c"><p class="cl-65fc51be"><span class="cl-65fb4102">n</span></p></th><th class="cl-65fc5d1d"><p class="cl-65fc51b4"><span class="cl-65fb4102">Mean (SE)</span></p></th><th class="cl-65fc5d12"><p class="cl-65fc51b4"><span class="cl-65fb4102">95% Confidence Interval</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-65fc5d26"><p class="cl-65fc51b4"><span class="cl-65fb4102">Dorsalis pedis</span></p></td><td class="cl-65fc5d27"><p class="cl-65fc51be"><span class="cl-65fb4102">107</span></p></td><td class="cl-65fc5d28"><p class="cl-65fc51b4"><span class="cl-65fb4102">116.7 (3.46)</span></p></td><td class="cl-65fc5d26"><p class="cl-65fc51b4"><span class="cl-65fb4102">(109.9 to 123.6)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65fc5d26"><p class="cl-65fc51b4"><span class="cl-65fb4102">Tibialis posterior</span></p></td><td class="cl-65fc5d27"><p class="cl-65fc51be"><span class="cl-65fb4102">107</span></p></td><td class="cl-65fc5d28"><p class="cl-65fc51b4"><span class="cl-65fb4102">118.0 (3.43)</span></p></td><td class="cl-65fc5d26"><p class="cl-65fc51b4"><span class="cl-65fb4102">(111.2 to 124.8)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-65fc5d30"><p class="cl-65fc51b4"><span class="cl-65fb4102">Difference</span></p></td><td class="cl-65fc5d31"><p class="cl-65fc51be"><span class="cl-65fb4102">107</span></p></td><td class="cl-65fc5d32"><p class="cl-65fc51b4"><span class="cl-65fb4102">-1.3 (1.31)</span></p></td><td class="cl-65fc5d30"><p class="cl-65fc51b4"><span class="cl-65fb4102">(-3.9 to 1.3)</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>The t-value is calculated as −0.96 with 106 degrees of freedom, providing a two-sided P-value of 0.34. Thus these data provide no evidence of a difference in systolic blood pressure between the two sites.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="jamovi-notes" class="level1 unnumbered">
<h1 class="unnumbered">Jamovi notes</h1>
<section id="checking-data-for-the-independent-samples-t-test" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="checking-data-for-the-independent-samples-t-test"><span class="header-section-number">5.4</span> Checking data for the independent samples t-test</h2>
<section id="examining-variable-distributions-by-a-second-variable" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="examining-variable-distributions-by-a-second-variable"><span class="header-section-number">5.4.1</span> Examining variable distributions by a second variable</h3>
<p>We can use <strong>Analyses &gt; Exploration &gt; Descriptives</strong> to obtain the distribution plots in <a href="#fig-mod05-bwt-gender" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>. Choose <code>birthweight</code> to appear in the <strong>Variables</strong> box, and <code>gender</code> as the <strong>Split by</strong> variable. Choose <strong>Density</strong> in the <strong>Plots</strong> section:</p>
<p>Jamovi also produces summary statistics for each level of the <strong>Split by</strong> variable, and we can select the statistics of interest in the <strong>Statistics</strong> section as necessary.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/mod05/jamovi/dist-by-1.png" class="img-fluid figure-img" style="width:66.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="independent-samples-t-test-1" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="independent-samples-t-test-1"><span class="header-section-number">5.5</span> Independent samples t-test</h2>
<p>To carry out an independent sample t-test, go to <strong>Analyses &gt; T-Tests &gt; Independent Samples T-Test</strong>. Move <code>birthweight</code> into <strong>Dependent variables</strong> and <code>gender</code> as the <strong>Grouping Variable</strong>. Because we don’t assume equal variances of <code>birthweight</code> for males and females, we tick the <strong>Welch’s</strong> box.</p>
<p>In order to obtain an estimate of the difference in means, with its 95% Confidence Interval, tick the relevant boxes in <strong>Additional Statistics</strong>:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/mod05/jamovi/ttest-1-unequal.png" class="img-fluid figure-img" style="width:66.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="checking-the-assumptions-for-a-paired-t-test" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="checking-the-assumptions-for-a-paired-t-test"><span class="header-section-number">5.6</span> Checking the assumptions for a Paired t-test</h2>
<p>Before performing a paired t-test, you must check that the assumptions for the test have been met. Using the dataset <code>mod05_ankle_bp.xls</code> to show that the difference between the pair of measurements between the sites is normally distributed, we first need to compute a new variable of the differences.</p>
<p>To create a new column at the end of your dataset, click a cell in the first empty column, then choose <strong>Data &gt; Compute</strong>. We want to compute <code>difference</code> as <code>sbp_dp − sbp_tp</code>, so we enter this in the formula box as below:</p>
<ol type="1">
<li>Specify the name of the variable to be created: here <code>difference</code></li>
<li>Click the <em>f <sub>x</sub></em> button to display a list of variable names in your dataset</li>
<li>Double-click the variable <code>sbp_dp</code> to bring it into the formula box</li>
<li>Type <code>-</code> to represent “minus”</li>
<li>Double-click the variable <code>sbp_tp</code> to bring it into the formula box (do not worry if your formula is underlined in red, this is simply a spell-check)</li>
<li>Click the up arrow to close the <strong>Compute</strong> dialog box</li>
</ol>
<p>(Note that steps 3 to 5 could also be completed by typing the formula.)</p>
<p>You will see a new column called <code>difference</code> which represents the difference between the two blood pressures.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/mod05/jamovi/ttest-paired-1.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>A density plot of the differences can be constructed in the usual way.</p>
</section>
<section id="paired-t-test" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="paired-t-test"><span class="header-section-number">5.7</span> Paired t-Test</h2>
<p>Using the same blood pressure data as previously, choose <strong>Analyses &gt; T-Tests &gt; Paired Samples T-Test</strong>. Select <code>sbp_dp</code> and <code>sbp_tp</code> as the <strong>Paired Variables</strong>.</p>
<p>To obtain more informative output, select <strong>Mean difference</strong> and <strong>Confidence interval</strong> as additional statistics. The dialog box will look like:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/mod05/jamovi/ttest-paired-2.png" class="img-fluid figure-img" style="width:66.0%"></p>
</figure>
</div>
</div>
</div>
<p>With the following output:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="img/mod05/jamovi/ttest-paired-3.png" class="img-fluid figure-img" style="width:66.0%"></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="r-notes" class="level1 unnumbered">
<h1 class="unnumbered">R notes</h1>
<section id="checking-data-for-the-independent-samples-t-test-1" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="checking-data-for-the-independent-samples-t-test-1"><span class="header-section-number">5.8</span> Checking data for the independent samples t-test</h2>
<section id="examining-variable-distributions-by-a-second-variable-1" class="level3" data-number="5.8.1">
<h3 data-number="5.8.1" class="anchored" data-anchor-id="examining-variable-distributions-by-a-second-variable-1"><span class="header-section-number">5.8.1</span> Examining variable distributions by a second variable</h3>
<p>We can use the a <code>splitBy</code> variable in the <code>descriptives</code> function in the <code>jmv</code> package to obtain summary statistics for each level of a grouping variable. Further, specifying <code>dens = TRUE</code> will produce density plots for the analysis variable for each level of the grouping variable.</p>
<p>For example, to create the distribution plots in <a href="#fig-mod05-bwt-gender" class="quarto-xref">Figure&nbsp;<span>5.1</span></a>, we can use</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>bwt <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/examples/mod05_birthweight.rds"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>bwt, <span class="at">vars=</span>birthweight, <span class="at">splitBy=</span>gender, <span class="at">dens=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                    
 ─────────────────────────────────────────────── 
                         gender    birthweight   
 ─────────────────────────────────────────────── 
   N                     Female             56   
                         Male               44   
   Missing               Female              0   
                         Male                0   
   Mean                  Female       3.587411   
                         Male         3.421364   
   Median                Female       3.530000   
                         Male         3.430000   
   Standard deviation    Female      0.3629788   
                         Male        0.3536165   
   Minimum               Female       2.950000   
                         Male         2.750000   
   Maximum               Female       4.250000   
                         Male         4.100000   
 ─────────────────────────────────────────────── </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-comparing-two-means_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="independent-samples-t-test-2" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="independent-samples-t-test-2"><span class="header-section-number">5.9</span> Independent samples t-test</h2>
<p>We can use the <code>ttestIS()</code> (t-test, independent samples) function from the <code>jmv</code> package to perform the independent samples t-test. We include the <code>meanDiff=TRUE</code> and <code>ci=TRUE</code> options to obtain the difference in means, with its 95% confidence interval. We can request a Welch’s test (which does not assume equal variances) by the <code>welchs=TRUE</code> option:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestIS</span>(<span class="at">data=</span>bwt, <span class="at">vars=</span>birthweight, <span class="at">group=</span>gender, <span class="at">meanDiff=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>, <span class="at">welchs=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 INDEPENDENT SAMPLES T-TEST

 Independent Samples T-Test                                                                                                          
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
                                 Statistic    df          p            Mean difference    SE difference    Lower         Upper       
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
   birthweight    Student's t     2.296556    98.00000    0.0237731          0.1660471       0.07230265    0.02256481    0.3095293   
                  Welch's t       2.303840    93.54377    0.0234458          0.1660471       0.07207403    0.02293328    0.3091609   
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
   Note. Hₐ μ &lt;sub&gt;Female&lt;/sub&gt; ≠ μ &lt;sub&gt;Male&lt;/sub&gt;</code></pre>
</div>
</div>
</section>
<section id="checking-the-assumptions-for-a-paired-t-test-1" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="checking-the-assumptions-for-a-paired-t-test-1"><span class="header-section-number">5.10</span> Checking the assumptions for a Paired t-test</h2>
<p>Before performing a paired t-test, you must check that the assumptions for the test have been met. Using the dataset <code>mod05_ankle_bp.xls</code> to show that the difference between the pair of measurements between the sites is normally distributed, we first need to compute a new variable of the differences and examine its distribution.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>sbp <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"data/examples/mod05_ankle_bp.xlsx"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>sbp<span class="sc">$</span>diff <span class="ot">=</span> sbp<span class="sc">$</span>sbp_dp <span class="sc">-</span> sbp<span class="sc">$</span>sbp_tp</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>sbp, <span class="at">vars=</span>diff, <span class="at">dens=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                        
 ─────────────────────────────────── 
                         diff        
 ─────────────────────────────────── 
   N                           107   
   Missing                       0   
   Mean                  -1.261682   
   Median                 0.000000   
   Standard deviation     13.56489   
   Minimum               -40.00000   
   Maximum                65.00000   
 ─────────────────────────────────── </code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-comparing-two-means_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>While there is a large difference in blood pressure (around 60 mmHg) that warrants further checking, the curve is roughly symmetric with an approximately Normal distribution.</p>
</section>
<section id="paired-t-test-1" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="paired-t-test-1"><span class="header-section-number">5.11</span> Paired t-Test</h2>
<p>To perform a paired t-test we will use the dataset <code>mod05_ankle_bp.xls</code>. We can perform a paired t-test using the <code>ttestPS()</code> function within the <code>jmv</code> package, where we defined the paired observations as: `pairs=list(list(i1 = ‘variable1’, i2 = ‘variable2’))</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ttestPS</span>(<span class="at">data=</span>sbp, <span class="at">pairs=</span><span class="fu">list</span>(<span class="fu">list</span>(<span class="at">i1 =</span> <span class="st">'sbp_dp'</span>, <span class="at">i2 =</span> <span class="st">'sbp_tp'</span>)), <span class="at">meanDiff=</span><span class="cn">TRUE</span>, <span class="at">ci=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 PAIRED SAMPLES T-TEST

 Paired Samples T-Test                                                                                                                   
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
                                      statistic     df          p            Mean difference    SE difference    Lower        Upper      
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
   sbp_dp    sbp_tp    Student's t    -0.9621117    106.0000    0.3381832          -1.261682         1.311368    -3.861596    1.338232   
 ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 
   Note. Hₐ μ &lt;sub&gt;Measure 1 - Measure 2&lt;/sub&gt; ≠ 0</code></pre>
</div>
</div>
<p>The syntax of the ttestPS function is a little cumbersome. The <code>t.test</code> function can be used as an alternative:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sbp<span class="sc">$</span>sbp_dp, sbp<span class="sc">$</span>sbp_tp, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  sbp$sbp_dp and sbp$sbp_tp
t = -0.96211, df = 106, p-value = 0.3382
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -3.861596  1.338232
sample estimates:
mean difference 
      -1.261682 </code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="activities" class="level1 unnumbered">
<h1 class="unnumbered">Activities</h1>
<section id="activity-5.1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.1">Activity 5.1</h3>
<p>Indicate what type of t-test could be used to analyse the data from the following studies and provide reasons:</p>
<ol type="a">
<li>A total of 60 university students are randomly assigned to undergo either behaviour therapy or Gestalt therapy. After twenty therapeutic sessions, each student earns a score on a mental health questionnaire.</li>
<li>A researcher wishes to determine whether attendance at a day care centre increases the scores of three year old twins on a motor skills test. Random assignment is used to decide which member from each of 30 pairs of twins attends the day care centre and which member stays at home.</li>
<li>A child psychologist assigns aggression scores to each of 10 children during two 60 minute observation periods separated by an intervening exposure to a series of violent TV cartoons.</li>
<li>A marketing researcher measures 100 doctors’ reports of the number of their patients asking them about a particular drug during the month before and the month after a major advertising campaign.</li>
</ol>
</section>
<section id="activity-5.2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.2">Activity 5.2</h3>
<p>A study was conducted to compare haemoglobin levels in the blood of children with and without cystic fibrosis. It is known that haemoglobin levels are normally distributed in children. The data are stored in Activity_5.2.csv as:</p>
<ul>
<li>cf: cystic fibrosis: 0=no, 1=yes</li>
<li>haem: haemoglobin (g/dL)</li>
</ul>
<ol type="a">
<li>State the appropriate null hypothesis and alternate hypothesis</li>
<li>Use jamovi or R to conduct an appropriate statistical test to evaluate the null hypothesis. Are the assumptions for the test met for this analysis to be valid?</li>
</ol>
</section>
<section id="activity-5.3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.3">Activity 5.3</h3>
<p>A randomised controlled trial (RCT) was carried out to investigate the effect of a new tablet supplement in increasing the hematocrit (%) value in anaemic participants. In the study, hematocrit was measured as the proportion of blood that is made up of red blood cells. Hematocrit levels are often lower in anaemic people who do not have sufficient healthy red blood cells. In the RCT, 33 people in the intervention group received the new supplement and 31 people in the control group received standard care (i.e.&nbsp;the usual supplement was given). After 4 weeks, hematocrit values were measured as entered in the files <code>Activity_S5.3.dta</code> and <code>Activity_S5.3.rds</code>. In the community, hematocrit levels are normally distributed.</p>
<ol type="a">
<li>State the research question and formulate a null hypothesis.</li>
<li>Use jamovi or R to conduct an appropriate statistical test to answer the research question. Before using the test, check the data to see if the assumptions required for the test are met.</li>
<li>Run your statistical test.</li>
<li>Construct a table to show how you would report your results and write a conclusion.</li>
</ol>
</section>
<section id="activity-5.4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-5.4">Activity 5.4</h3>
<p>A total of 41 babies aged 6 months to 2 years with haemangioma (birth mark) were enrolled in a study to test the effect of a new topical medication in reducing the volume of their haemangioma. Parents were asked to apply the medication twice daily. The volume (in mm3) of the haemangioma was measured at enrolment and again after 12 weeks of using the medication.</p>
<p>Analyse these data fully to answer the research question. Are there any limitations of this study?</p>
</section>
<section id="supplementary-activity-5.5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="supplementary-activity-5.5">Supplementary Activity 5.5</h3>
<p>A study was conducted to investigate cardiovascular health of Australians. In this study heart rates were recorded by a heart rate monitor on each participant following 30 minutes of intense aerobic exercise. The researchers are interested in whether there is a difference in the mean post-exercise heart rates of females aged 20 – 24 years compared to females aged 25 – 30 years.</p>
<p>A dataset containing the study information is provided in the file Activity_5.5_heartrate.csv. There are 149 observations in the dataset with the following variables:</p>
<ul>
<li>id: id number</li>
<li>agegroup: age range of the females (1 = 20 – 24 years; 2 = 25 – 30 years)</li>
<li>heartrate: heart rate (beats/minute)</li>
</ul>
<p>Analyse these data to answer the research question. Write a brief report summarising your results and state your conclusion.</p>
</section>
<section id="activity-5.6" class="level3" data-number="5.11.1">
<h3 data-number="5.11.1" class="anchored" data-anchor-id="activity-5.6"><span class="header-section-number">5.11.1</span> Activity 5.6</h3>
<p>A study was conducted to assess the effectiveness of a health promotion program to improve the fitness of school children. The fitness of 58 children from an inner-city school was assessed by measuring the total distance each child could run in a 10-minute period.</p>
<p>The following data are stored in Activity_5.6_fitness.csv:</p>
<ul>
<li>id: participant ID</li>
<li>before: 10-minute running distance before the program (metres)</li>
<li>after: 10-minute running distance after the program (metres)</li>
</ul>
<p>Analyse these data to assess whether there has been a change in running distance after the health promotion campaign. Write a brief report summarising your results and state your conclusion.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bland15" class="csl-entry" role="listitem">
Bland, Martin. 2015. <em>An <span>Introduction</span> to <span>Medical Statistics</span></em>. 4th Edition. Oxford, New York: Oxford University Press.
</div>
<div id="ref-delacre_etal17" class="csl-entry" role="listitem">
Delacre, Marie, Daniël Lakens, and Christophe Leys. 2017. <span>“Why <span>Psychologists Should</span> by <span>Default Use Welch</span>’s t-Test <span>Instead</span> of <span>Student</span>’s t-Test”</span> 30 (1): 92. <a href="https://doi.org/10.5334/irsp.82">https://doi.org/10.5334/irsp.82</a>.
</div>
<div id="ref-kirkwood_sterne01" class="csl-entry" role="listitem">
Kirkwood, Betty, and Jonathan Sterne. 2001. <em>Essentials of <span>Medical Statistics</span></em>. 2nd edition. Malden, Mass: Wiley-Blackwell.
</div>
<div id="ref-ruxton06" class="csl-entry" role="listitem">
Ruxton, Graeme D. 2006. <span>“The Unequal Variance t-Test Is an Underused Alternative to <span>Student</span>’s t-Test and the <span>Mann</span>–<span>Whitney U</span> Test.”</span> <em>Behavioral Ecology</em> 17 (4): 688–90. <a href="https://doi.org/10.1093/beheco/ark016">https://doi.org/10.1093/beheco/ark016</a>.
</div>
<div id="ref-west21" class="csl-entry" role="listitem">
West, Robert M. 2021. <span>“Best Practice in Statistics: <span>Use</span> the <span>Welch</span> t-Test When Testing the Difference Between Two Groups.”</span> <em>Annals of Clinical Biochemistry</em> 58 (4): 267–69. <a href="https://doi.org/10.1177/0004563221992088">https://doi.org/10.1177/0004563221992088</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04-hypothesis-testing.html" class="pagination-link" aria-label="An introduction to hypothesis testing">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">An introduction to hypothesis testing</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06-proportions.html" class="pagination-link" aria-label="Summary statistics for binary data">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>