<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.31">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>9&nbsp; Analysing non-normal data – PHCM9795: Foundations of Biostatistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./98.1-appendix1.html" rel="next">
<link href="./08-correlation-and-regression.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-29fdfc89ac7fc112ecf2c1fbf9d5ebfc.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9a71a2450f5674972ff858c43d8deec0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>

      .quarto-title-block .quarto-title-banner {
        background: #ffdc00;
      }
</style>
<link href="site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="site_libs/tabwid-1.1.3/tabwid.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-non-parametrics.html"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PHCM9795: Foundations of Biostatistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction to biostatistics and data fundamentals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Categorical data, presentation guidelines and probability distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-precision.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Continuous probability distributions, sampling and precision</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">An introduction to hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-comparing-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Comparing the means of two groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Summary statistics for binary data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-testing-proportions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Hypothesis testing for categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-correlation-and-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-non-parametrics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Analysing non-normal data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./98.1-appendix1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Appendix</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link active" data-scroll-target="#learning-objectives">Learning objectives</a></li>
  <li><a href="#optional-readings" id="toc-optional-readings" class="nav-link" data-scroll-target="#optional-readings">Optional readings</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">9.1</span> Introduction</a></li>
  <li><a href="#transforming-non-normally-distributed-variables" id="toc-transforming-non-normally-distributed-variables" class="nav-link" data-scroll-target="#transforming-non-normally-distributed-variables"><span class="header-section-number">9.2</span> Transforming non-normally distributed variables</a>
  <ul class="collapse">
  <li><a href="#worked-example" id="toc-worked-example" class="nav-link" data-scroll-target="#worked-example"><span class="header-section-number">9.2.1</span> Worked Example</a></li>
  </ul></li>
  <li><a href="#non-parametric-significance-tests" id="toc-non-parametric-significance-tests" class="nav-link" data-scroll-target="#non-parametric-significance-tests"><span class="header-section-number">9.3</span> Non-parametric significance tests</a>
  <ul class="collapse">
  <li><a href="#ranking-variables" id="toc-ranking-variables" class="nav-link" data-scroll-target="#ranking-variables"><span class="header-section-number">9.3.1</span> Ranking variables</a></li>
  </ul></li>
  <li><a href="#non-parametric-test-for-two-independent-samples-wilcoxon-ranked-sum-test" id="toc-non-parametric-test-for-two-independent-samples-wilcoxon-ranked-sum-test" class="nav-link" data-scroll-target="#non-parametric-test-for-two-independent-samples-wilcoxon-ranked-sum-test"><span class="header-section-number">9.4</span> Non-parametric test for two independent samples (Wilcoxon ranked sum test)</a></li>
  <li><a href="#non-parametric-test-for-paired-data-wilcoxon-signed-rank-test" id="toc-non-parametric-test-for-paired-data-wilcoxon-signed-rank-test" class="nav-link" data-scroll-target="#non-parametric-test-for-paired-data-wilcoxon-signed-rank-test"><span class="header-section-number">9.5</span> Non-parametric test for paired data (Wilcoxon signed-rank test)</a>
  <ul class="collapse">
  <li><a href="#worked-example-1" id="toc-worked-example-1" class="nav-link" data-scroll-target="#worked-example-1"><span class="header-section-number">9.5.1</span> Worked Example</a></li>
  </ul></li>
  <li><a href="#non-parametric-estimates-of-correlation" id="toc-non-parametric-estimates-of-correlation" class="nav-link" data-scroll-target="#non-parametric-estimates-of-correlation"><span class="header-section-number">9.6</span> Non-parametric estimates of correlation</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">9.7</span> Summary</a></li>
  <li><a href="#jamovi-notes" id="toc-jamovi-notes" class="nav-link" data-scroll-target="#jamovi-notes">jamovi notes</a>
  <ul class="collapse">
  <li><a href="#transforming-non-normally-distributed-variables-1" id="toc-transforming-non-normally-distributed-variables-1" class="nav-link" data-scroll-target="#transforming-non-normally-distributed-variables-1"><span class="header-section-number">9.8</span> Transforming non-normally distributed variables</a></li>
  <li><a href="#wilcoxon-ranked-sum-test" id="toc-wilcoxon-ranked-sum-test" class="nav-link" data-scroll-target="#wilcoxon-ranked-sum-test"><span class="header-section-number">9.9</span> Wilcoxon ranked-sum test</a></li>
  <li><a href="#wilcoxon-matched-pairs-signed-rank-test" id="toc-wilcoxon-matched-pairs-signed-rank-test" class="nav-link" data-scroll-target="#wilcoxon-matched-pairs-signed-rank-test"><span class="header-section-number">9.10</span> Wilcoxon matched-pairs signed-rank test</a></li>
  <li><a href="#estimating-rank-correlation-coefficients" id="toc-estimating-rank-correlation-coefficients" class="nav-link" data-scroll-target="#estimating-rank-correlation-coefficients"><span class="header-section-number">9.11</span> Estimating rank correlation coefficients</a></li>
  </ul></li>
  <li><a href="#r-notes" id="toc-r-notes" class="nav-link" data-scroll-target="#r-notes">R notes</a>
  <ul class="collapse">
  <li><a href="#transforming-non-normally-distributed-variables-2" id="toc-transforming-non-normally-distributed-variables-2" class="nav-link" data-scroll-target="#transforming-non-normally-distributed-variables-2"><span class="header-section-number">9.12</span> Transforming non-normally distributed variables</a></li>
  <li><a href="#wilcoxon-ranked-sum-test-1" id="toc-wilcoxon-ranked-sum-test-1" class="nav-link" data-scroll-target="#wilcoxon-ranked-sum-test-1"><span class="header-section-number">9.13</span> Wilcoxon ranked-sum test</a></li>
  <li><a href="#wilcoxon-matched-pairs-signed-rank-test-1" id="toc-wilcoxon-matched-pairs-signed-rank-test-1" class="nav-link" data-scroll-target="#wilcoxon-matched-pairs-signed-rank-test-1"><span class="header-section-number">9.14</span> Wilcoxon matched-pairs signed-rank test</a></li>
  <li><a href="#estimating-rank-correlation-coefficients-1" id="toc-estimating-rank-correlation-coefficients-1" class="nav-link" data-scroll-target="#estimating-rank-correlation-coefficients-1"><span class="header-section-number">9.15</span> Estimating rank correlation coefficients</a></li>
  </ul></li>
  <li><a href="#activities" id="toc-activities" class="nav-link" data-scroll-target="#activities">Activities</a>
  <ul class="collapse">
  <li><a href="#activity-9.1" id="toc-activity-9.1" class="nav-link" data-scroll-target="#activity-9.1">Activity 9.1</a></li>
  <li><a href="#activity-9.2" id="toc-activity-9.2" class="nav-link" data-scroll-target="#activity-9.2">Activity 9.2</a></li>
  <li><a href="#activity-9.3" id="toc-activity-9.3" class="nav-link" data-scroll-target="#activity-9.3">Activity 9.3</a></li>
  <li><a href="#supplementary-activity-9.4" id="toc-supplementary-activity-9.4" class="nav-link" data-scroll-target="#supplementary-activity-9.4">Supplementary Activity 9.4</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="learning-objectives" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="learning-objectives">Learning objectives</h2>
<p>By the end of this module you will be able to:</p>
<ul>
<li>Transform non-normally distributed variables;</li>
<li>Explain the purpose of non-parametric statistics and key principles for their use;</li>
<li>Calculate ranks for variables;</li>
<li>Conduct and interpret a non-parametric independent samples significance test;</li>
<li>Conduct and interpret a non-parametric paired samples significance test;</li>
<li>Calculate and interpret the Spearman rank correlation coefficient.</li>
</ul>
</section>
<section id="optional-readings" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="optional-readings">Optional readings</h2>
<p><span class="citation" data-cites="kirkwood_sterne01">Kirkwood and Sterne (<a href="references.html#ref-kirkwood_sterne01" role="doc-biblioref">2001</a>)</span>; Chapter 13. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=624728">[UNSW Library Link]</a></p>
<p><span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>; Chapter 12. <a href="http://er1.library.unsw.edu.au/er/cgi-bin/eraccess.cgi?url=https://ebookcentral.proquest.com/lib/unsw/detail.action?docID=5891730">[UNSW Library Link]</a></p>
</section>
<section id="introduction" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">9.1</span> Introduction</h2>
<p>In general, parametric statistics are preferred for reporting data because the summary statistics (mean, standard deviation, standard error of the mean etc) and the tests used (t-tests, correlation, regression etc) are familiar and the results are easy to communicate. However, non-parametric tests can be used if data are not normally distributed. Non-parametric tests make fewer assumptions about the distribution of the data.</p>
</section>
<section id="transforming-non-normally-distributed-variables" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="transforming-non-normally-distributed-variables"><span class="header-section-number">9.2</span> Transforming non-normally distributed variables</h2>
<p>When a variable has a skewed distribution, one possibility is to transform the data to a new variable to try and obtain a normal or near normal distribution. Methods to transform non-normally distributed data include logarithmic transformation of each data point, or using the square root or the square or the inverse (i.e.&nbsp;1/x) etc.</p>
<section id="worked-example" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="worked-example"><span class="header-section-number">9.2.1</span> Worked Example</h3>
<p>We have data from 132 patients who had a hospital stay following admission to ICU available on Moodle (<code>mod09_infection.dta</code> and <code>mod09_infection.rds</code>). The distribution of the length of stay for these patients is shown in the density plot in <a href="#fig-mod09-los" class="quarto-xref">Figure&nbsp;<span>9.1</span></a>. As is common with variables that record time, the data are skewed with many patients having relatively short stays and a few patients having very long hospital stays. Clearly, it would be inappropriate to use parametric statistical methods for these data.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod09-los" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mod09-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/mod09/mod09-los-dist.png" class="img-fluid figure-img" style="width:66.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mod09-los-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.1: Length of hospital stay for 132 patients
</figcaption>
</figure>
</div>
</div>
</div>
<p>When data are positively skewed, as shown in <a href="#fig-mod09-los" class="quarto-xref">Figure&nbsp;<span>9.1</span></a>, a logarithmic transformation can often make the data closer to being normally distributed. This is the most common transformation used. You should note, however, that the logarithmic function cannot handle 0 or negative values. One way to deal with zeros in a set of data is to add 1 to each value before taking the logarithm.</p>
<p>We would generate a new variable, as shown in the jamovi or R notes. As the minimum length of stay in these sample data was 0, we have added 1 to each length of stay before taking the logarithm. The distribution of the logarithm of (length of stay + 1) is shown in <a href="#fig-mod09-lnlos" class="quarto-xref">Figure&nbsp;<span>9.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod09-lnlos" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mod09-lnlos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/mod09/mod09-lnlos-dist.png" class="img-fluid figure-img" style="width:66.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mod09-lnlos-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.2: Distribution of log transformed (length of stay + 1)
</figcaption>
</figure>
</div>
</div>
</div>
<p>The distribution now appears much more bell shaped. <a href="#tbl-los-desc" class="quarto-xref">Table&nbsp;<span>9.1</span></a> shows the descriptive statistics for length of stay before and after logarithmic transformation. Before transformation, the SD is almost as large as the mean value which indicates that the data are skewed and that these statistics are not an accurate description of the centre and spread of the data.</p>
<div id="tbl-los-desc" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-los-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.1: Summary statistics for untransformed and transformed length of stay
</figcaption>
<div aria-describedby="tbl-los-desc-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 22%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Length of stay</th>
<th>log(Length of stay + 1)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mean (Standard deviation)</td>
<td>38.1 (35.78)</td>
<td>3.41 (0.715)</td>
</tr>
<tr class="even">
<td>Mean: 95% confidence interval</td>
<td>31.9 to 44.2</td>
<td>3.29 to 3.53</td>
</tr>
<tr class="odd">
<td>Median [Interquartile range]</td>
<td>27 [21 to 42]</td>
<td>3.3 [3.1 to 3.8]</td>
</tr>
<tr class="even">
<td>Range</td>
<td>0 to 244</td>
<td>0 to 5.5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The mean and standard deviation of the transformed length of stay are in log base e (i.e.&nbsp;ln) units. If we raise the mean of the log of length of stay to the power of <span class="math inline">\(e\)</span>, it returns a value of 30.2 days (<span class="math inline">\(e^{3.41}=30.2\)</span>).</p>
<p>Technically, this is called the geometric mean of the data, and it has a different interpretation to the usual mean, the arithmetic mean. This is a much better estimate in this case of the “average” length of stay than the mean of 38.1 days (95% CI 31.9, 44.2 days) obtained from the non-transformed positively skewed data. Note that, if you have added 1 to your data to deal with 0 values, the back-transformed estimate is <em>approximately</em> equal to the geometric mean.</p>
<p>This set of data also includes a variable summarising whether a patient acquired a nosocomial infection (also known as healthcare-associated infections), which are infections that develop while undergoing medical treatment but were absent at the time of admission.</p>
<p>If we were testing the hypothesis that there was a difference in length of stay between groups (status of nosocomial infection), t-tests should not be used with length of stay, but could be used for the log transformed variable, which is approximately normally distributed. The output from the t-test of the log-transformed length of stay is shown in <a href="#tbl-los-ttest" class="quarto-xref">Table&nbsp;<span>9.2</span></a>. This is done using the t-test shown in Module 5.</p>
<div id="tbl-los-ttest" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-los-ttest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.2: Summary statistics for transformed length of stay
</figcaption>
<div aria-describedby="tbl-los-ttest-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Nosocomial infection</th>
<th>n</th>
<th>Mean (SE)</th>
<th style="text-align: center;">95% Confidence interval</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>No</td>
<td>106</td>
<td>3.33 (0.068)</td>
<td style="text-align: center;">3.19 to 3.46</td>
</tr>
<tr class="even">
<td>Yes</td>
<td>26</td>
<td>3.73 (0.136)</td>
<td style="text-align: center;">3.45 to 4.01</td>
</tr>
<tr class="odd">
<td>Difference (Yes - No)</td>
<td></td>
<td>0.39 (0.153)</td>
<td style="text-align: center;">0.09 to 0.70</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Here, a two-sample t-test gives a test statistic of 2.59 with 130 degrees of freedom, and a P-value of 0.01.</p>
<p>As explained above, the estimated statistics would need to be converted back to the units in which the variable was measured. From <a href="#tbl-los-ttest" class="quarto-xref">Table&nbsp;<span>9.2</span></a>, we can take the exponential of the corresponding log-transformed values:</p>
<ul>
<li>the geometric mean of the infected group is approximately 41.5 days with a 95% confidence interval from 31.4 to 55.0 days.</li>
<li>the geometric mean of the uninfected group is approximately 27.9 days with a 95% confidence interval from 24.4 to 31.9 days.</li>
</ul>
</section>
</section>
<section id="non-parametric-significance-tests" class="level2" data-number="9.3">
<h2 data-number="9.3" class="anchored" data-anchor-id="non-parametric-significance-tests"><span class="header-section-number">9.3</span> Non-parametric significance tests</h2>
<p>It is often not possible or sensible to transform a non-normal distribution, for example if there are too many zero values or when we simply want to compare groups using the unit in which the measurement was taken (e.g.&nbsp;length of stay). For this, non-parametric significance tests can be used but the general idea behind these tests is that the data values are replaced by ranks. This also protects against outliers having too much influence.</p>
<section id="ranking-variables" class="level3" data-number="9.3.1">
<h3 data-number="9.3.1" class="anchored" data-anchor-id="ranking-variables"><span class="header-section-number">9.3.1</span> Ranking variables</h3>
<p><a href="#tbl-9-1" class="quarto-xref">Table&nbsp;<span>9.3</span></a> shows how ranks are calculated for the first 21 patients in the length-of-stay data. First the data are sorted in order of their magnitude (from the lowest value to the highest) ignoring the group variable. Each data point is then assigned a rank. Data points that are equal are assigned the mean of their ranks. Thus, the two lengths of stay of 11 days share the ranks 4 and 5, and have a mean rank of 4.5. Similarly, there are 5 people with a length of stay of 14 days and these share the ranks 9 to 13, the mean of which is 11. Once ranks are computed they are assigned to each of the two groups and summed within each group.</p>
<div class="cell">
<div id="tbl-9-1" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-9-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.3: Transforming data to ranks (first 21 participants)
</figcaption>
<div aria-describedby="tbl-9-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-73bd006e{}.cl-73b93b8c{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-73baaf08{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-73baaf09{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-73bac2d6{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73bac2e0{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73bac2e1{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73bac2e2{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73bac2ea{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73bac2eb{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-73bd006e"><thead><tr style="overflow-wrap:break-word;"><th class="cl-73bac2d6"><p class="cl-73baaf08"><span class="cl-73b93b8c">ID</span></p></th><th class="cl-73bac2e0"><p class="cl-73baaf09"><span class="cl-73b93b8c">Infection</span></p></th><th class="cl-73bac2d6"><p class="cl-73baaf08"><span class="cl-73b93b8c">Length of stay</span></p></th><th class="cl-73bac2d6"><p class="cl-73baaf08"><span class="cl-73b93b8c">Rank</span></p></th><th class="cl-73bac2d6"><p class="cl-73baaf08"><span class="cl-73b93b8c">Infection=no</span></p></th><th class="cl-73bac2d6"><p class="cl-73baaf08"><span class="cl-73b93b8c">Infection=Yes</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">32</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">1.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">1.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">33</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">1</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">2.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">2.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">12</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">9</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">3.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">3.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">22</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">4.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">4.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">16</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">4.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">4.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">28</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">Yes</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">12</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">6.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">6.0</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">27</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">13</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">7.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">7.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">20</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">13</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">7.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">7.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">24</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">14</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">14</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">130</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">14</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">10</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">14</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">25</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">14</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">11.0</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">19</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">30</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">23</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">14</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">15</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">17</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">13</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">17</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">21</span></p></td><td class="cl-73bac2e2"><p class="cl-73baaf09"><span class="cl-73b93b8c">Yes</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">17</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td><td class="cl-73bac2e1"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73bac2ea"><p class="cl-73baaf08"><span class="cl-73b93b8c">17</span></p></td><td class="cl-73bac2eb"><p class="cl-73baaf09"><span class="cl-73b93b8c">No</span></p></td><td class="cl-73bac2ea"><p class="cl-73baaf08"><span class="cl-73b93b8c">17</span></p></td><td class="cl-73bac2ea"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td><td class="cl-73bac2ea"><p class="cl-73baaf08"><span class="cl-73b93b8c">20.5</span></p></td><td class="cl-73bac2ea"><p class="cl-73baaf08"><span class="cl-73b93b8c"></span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>By assigning ranks to individuals, we lose information about their actual values and this makes it more difficult to detect a difference. However, outliers and extreme values in the data are brought back closer to the data so that they are less influential. For this reason, non-parametric tests have less power than parametric tests and they require much larger differences in the data to show statistical significance between groups.</p>
</section>
</section>
<section id="non-parametric-test-for-two-independent-samples-wilcoxon-ranked-sum-test" class="level2" data-number="9.4">
<h2 data-number="9.4" class="anchored" data-anchor-id="non-parametric-test-for-two-independent-samples-wilcoxon-ranked-sum-test"><span class="header-section-number">9.4</span> Non-parametric test for two independent samples (Wilcoxon ranked sum test)</h2>
<p>The non-parametric equivalent to an independent samples t-test (Module 5) is the Wilcoxon ranked sum test, also known as the Mann-Whitney U test. This can be obtained using the <code>Mann-Whitney U</code> option in jamovi, and the <code>wilcox.test</code> in R.</p>
<p>The assumption for this test is that the distributions of the two populations have the same general shape. If this assumption is met, then this test evaluates the null hypothesis that the medians of the two populations are equal. This test does not assume that the populations are normally distributed, nor that their variances are equal.</p>
<p>Conducting the Wilcoxon ranked sum test for our length of stay data yields a P-value of 0.014, providing evidence of a difference in the median length of stay between the groups.</p>
<p>This P-value should be provided alongside non-parametric summary statistics such as medians and inter-quartile ranges. In our example, we can obtain the median length of stay values of 24 (Interquartile Range: 19 to 40 days) in the group with no infection and 37 (Interquartile Range: 24 to 50 days) in the group with infection.</p>
</section>
<section id="non-parametric-test-for-paired-data-wilcoxon-signed-rank-test" class="level2" data-number="9.5">
<h2 data-number="9.5" class="anchored" data-anchor-id="non-parametric-test-for-paired-data-wilcoxon-signed-rank-test"><span class="header-section-number">9.5</span> Non-parametric test for paired data (Wilcoxon signed-rank test)</h2>
<p>There are two types of non-parametric tests for paired data, called the Sign test and the Wilcoxon signed rank test. In practice, the Sign test is rarely used and will not be discussed in this course.</p>
<p>If the differences between two paired measurements are not normally distributed, a non-parametric equivalent of a paired t-test (Module 5) should be used. The equivalent test is the Wilcoxon matched-pairs signed rank test, also simply called the Wilcoxon matched-pairs test. This test is resistant to outliers in the data, however the proportion of outliers in the sample should be small. This test evaluates the null hypothesis that the median of the paired differences is equal to zero.</p>
<p>In this test, the absolute differences between the paired scores are ranked and the difference scores that are equal to zero (i.e.&nbsp;scores where there is no difference between the pairs) are excluded. Note that the power of the test (the ability to detect an effect if there truly is an effect) reduces in the presence of zero differences, as the effective sample size (the number of non-zero differences) is reduced.</p>
<section id="worked-example-1" class="level3" data-number="9.5.1">
<h3 data-number="9.5.1" class="anchored" data-anchor-id="worked-example-1"><span class="header-section-number">9.5.1</span> Worked Example</h3>
<p>A crossover trial is done to compare symptom scores for two drugs in 11 people with arthritis (higher scores indicate more severe symptoms). The data are contained in datafile file <code>mod09_arthritis.csv</code>. The data are shown in <a href="#tbl-9-2" class="quarto-xref">Table&nbsp;<span>9.4</span></a>.</p>
<div class="cell">
<div id="tbl-9-2" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-9-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9.4: Arthritis symptom scores for 11 patients after administering two drugs
</figcaption>
<div aria-describedby="tbl-9-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-73c66136{}.cl-73c3a77a{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-73c4c0b0{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-73c4cc04{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73c4cc05{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73c4cc06{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-73c66136"><thead><tr style="overflow-wrap:break-word;"><th class="cl-73c4cc04"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">Patient ID</span></p></th><th class="cl-73c4cc04"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">Score: Drug 1</span></p></th><th class="cl-73c4cc04"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">Score: Drug 2</span></p></th><th class="cl-73c4cc04"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">Difference (Drug 2 - Drug 1)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">1</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">3</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">4</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">2</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">2</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">7</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">5</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">3</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">3</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">4</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">4</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">8</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">10</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">2</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">5</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">6</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">8</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">2</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">6</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">6</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">1</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">-5</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">7</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">2</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">6</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">4</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">8</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">3</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">7</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">4</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">9</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">5</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">8</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">3</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">10</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">9</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">10</span></p></td><td class="cl-73c4cc05"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">1</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73c4cc06"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">11</span></p></td><td class="cl-73c4cc06"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">7</span></p></td><td class="cl-73c4cc06"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">8</span></p></td><td class="cl-73c4cc06"><p class="cl-73c4c0b0"><span class="cl-73c3a77a">1</span></p></td></tr></tbody></table></div>
</div>
</div>
</figure>
</div>
</div>
<p>The data shows that there is 1 person who has a negative difference, where the symptom score on drug 2 that is smaller than that for drug 1 (i.e., drug 2 is better than drug 1); and 10 people who have a positive difference. No one has the same score for both drugs.</p>
<p>Before doing the analysis let us examine the distribution of the difference of symptom scores between the two drugs. As in Module 5, we first need to compute the difference between the symptom scores. To examine the distribution, we construct a distribution plot as shown in <a href="#fig-mod09-diff-hist" class="quarto-xref">Figure&nbsp;<span>9.3</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mod09-diff-hist" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mod09-diff-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="img/mod09/mod09-diff-dist.png" class="img-fluid figure-img" style="width:66.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mod09-diff-hist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9.3: Distribution of difference in symptom scores between Drug 1 and Drug 2
</figcaption>
</figure>
</div>
</div>
</div>
<p>The plot shows that the differences are not normally distributed. The data looks weirdly negatively skewed with a gap in values around -2.5. Therefore, it would not be appropriate to conduct a paired t-test. Hence, we conduct a non-parametric paired test (Wilcoxon matched-pairs signed-rank test).</p>
<p>The P-value obtained from this test is 0.049. Thus, there is evidence of a difference in symptom scores between the two drugs.</p>
</section>
</section>
<section id="non-parametric-estimates-of-correlation" class="level2" data-number="9.6">
<h2 data-number="9.6" class="anchored" data-anchor-id="non-parametric-estimates-of-correlation"><span class="header-section-number">9.6</span> Non-parametric estimates of correlation</h2>
<p>Estimating correlation using Pearson’s correlation coefficient can be problematic when bivariate Normality cannot be assumed, or in the presence of outliers or skewness. There are two commonly used non-parametric alternatives to Pearson’s correlation coefficient: Spearman’s rank correlation (<span class="math inline">\(\rho\)</span> or rho), and Kendall’s rank correlation (<span class="math inline">\(\tau\)</span> or tau).</p>
<p>When estimating the correlation between x and y, Spearman’s rank correlation essentially replaces the observations x and y by their ranks, and calculates the correlation between the ranks. Kendall’s rank correlation compares the ranks between every possible combination of pairs of data to measure concordance: whether high values for x tend to be associated with high values for y (positively correlated) or low values of y (negatively correlated).</p>
<p>In terms of which is the more appropriate measure to use, the following passage from An Introduction to Medical Statistics (<span class="citation" data-cites="bland15">Bland (<a href="references.html#ref-bland15" role="doc-biblioref">2015</a>)</span>) provides some guidance:</p>
<blockquote class="blockquote">
<p>“Why have two different rank correlation coefficients? Spearman’s <span class="math inline">\(\rho\)</span> is older than Kendall’s <span class="math inline">\(\tau\)</span>, and can be thought of as a simple analogue of the product moment correlation coefficient, Pearson’s r. Kendall’s <span class="math inline">\(\tau\)</span> is a part of a more general and consistent system of ranking methods, and has a direct interpretation, as the difference between the proportions of concordant and discordant pairs. In general, the numerical value of <span class="math inline">\(\rho\)</span> is greater than that of <span class="math inline">\(\tau\)</span>. It is not possible to calculate <span class="math inline">\(\tau\)</span> from <span class="math inline">\(\rho\)</span> or <span class="math inline">\(\rho\)</span> from <span class="math inline">\(\tau\)</span>, they measure different sorts of correlation. <span class="math inline">\(\rho\)</span> gives more weight to reversals of order when data are far apart in rank than when there is a reversal close together in rank, <span class="math inline">\(\tau\)</span> does not. However, in terms of tests of significance, both have the same power to reject a false null hypothesis, so for this purpose it does not matter which is used.”</p>
</blockquote>
<p>We will illustrate estimating rank correlation using the data <code>mod08_lung_function.dta</code> or <code>mod08_lung_function.rds</code>, which has information about height and lung function collected from a sample of 120 adults.</p>
<p>The Spearman rank correlation coefficient is estimated as 0.75, demonstrating a positive association between height and FVC. The Kendall rank correlation coefficient is estimated as 0.56, again demonstrating a positive association between height and FVC.</p>
</section>
<section id="summary" class="level2" data-number="9.7">
<h2 data-number="9.7" class="anchored" data-anchor-id="summary"><span class="header-section-number">9.7</span> Summary</h2>
<p>In this module, we have presented methods to conduct a hypothesis test with data that are not normally distributed. Non-parametric methods do not assume any distribution for the data and use significance tests based on ranks or sign (or both). A non-parametric test is always less powerful than its equivalent parametric test if the data are normally distributed and so whenever possible parametric significance tests should be used. In some cases when data are not normally distributed with a reasonably large sample size, the data can be transformed (most commonly by log transformation) to make the distribution normal. A parametric significance test should then be used with the transformed data to test the hypothesis.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="jamovi-notes" class="level1 unnumbered">
<h1 class="unnumbered">jamovi notes</h1>
<section id="transforming-non-normally-distributed-variables-1" class="level2" data-number="9.8">
<h2 data-number="9.8" class="anchored" data-anchor-id="transforming-non-normally-distributed-variables-1"><span class="header-section-number">9.8</span> Transforming non-normally distributed variables</h2>
<p>One option for dealing with a non-normally distributed varaible is to transform it into its square, square root or logarithmic value. The new transformed variable may be normally distributed and therefore a parametric test can be used. First we check the distribution of the variable for normality, e.g.&nbsp;by plotting a density plot.</p>
<p>You can calculate a new, transformed, variable using <strong>Data &gt; Compute</strong>. For example, to create a new column of data based on the log of length of stay:</p>
<ul>
<li>click into an empty column at the end of the spreadsheet</li>
<li>click <strong>Data &gt; Compute</strong></li>
<li>provide a name for the new variable, here <code>log(length of stay + 1)</code></li>
<li>enter the formula for the new variable in the <em>f<sub>x</sub></em> box, here <code>LN(los + 1)</code></li>
<li>hit enter to create the new column:</li>
</ul>
<p><img src="img/mod09/jamovi/mod09-gen1.png" class="img-fluid"></p>
<p>You can now check whether this logged variable is normally distributed as described in Module 2, for example by plotting a density plot as shown in Figure 9.2.</p>
<p>To obtain the back-transformed mean, we can use a calculator to calculate the exponential mean:</p>
<p><span class="math inline">\(e^{3.407232} = 30.18\)</span></p>
<p>If your transformed variable is approximately normally distributed, you can apply parametric tests such as the t-test. In the Worked Example 9.1 dataset, the variable <code>infect</code> (presence of nosocomial infection) is a binary categorical variable. To test the hypothesis that patients with nosocomial infection have a different length of stay to patients without infection, you can conduct a t-test on the <code>log(length of stay + 1)</code> variable. You will need to back transform your mean values, as shown in Worked Example 9.1 in the course notes when reporting your results.</p>
</section>
<section id="wilcoxon-ranked-sum-test" class="level2" data-number="9.9">
<h2 data-number="9.9" class="anchored" data-anchor-id="wilcoxon-ranked-sum-test"><span class="header-section-number">9.9</span> Wilcoxon ranked-sum test</h2>
<p>The Wilcoxon ranked-sum test will be demonstrated using the length of stay data in <code>mod09_infection.rds</code>. Here, our continuous variable is <code>los</code> and the grouping variable is <code>infect</code>. Note that jamovi uses calls the Wilcoxon ranked-sum test the <strong>Mann-Whitney U</strong> test. The two tests are equivalent.</p>
<p>The Wilcoxon ranked-sum test is conducted in <strong>Analyses &gt; T-Tests &gt; Independent Samples T-Test</strong> in jamovi. The screen is set up in the same way as for a two-sample t-test. To conduct the Wilcoxon ranked-sum test, untick the <strong>Student’s</strong> box and click the <strong>Mann-Whitney U</strong> box in the <strong>Tests</strong> section:</p>
<p><img src="img/mod09/jamovi/mod09-wilcoxon.png" class="img-fluid"></p>
<p>Note that the result appears without any descriptive analyses. You should obtain the appropriate descriptive statistics in the usual way.</p>
<p><img src="img/mod09/jamovi/mod09-wilcoxon-result.png" class="img-fluid" style="width:50.0%"></p>
</section>
<section id="wilcoxon-matched-pairs-signed-rank-test" class="level2" data-number="9.10">
<h2 data-number="9.10" class="anchored" data-anchor-id="wilcoxon-matched-pairs-signed-rank-test"><span class="header-section-number">9.10</span> Wilcoxon matched-pairs signed-rank test</h2>
<p>The Wilcoxon ranked-sum test is conducted in jamovi using <strong>Analyses &gt; T-Tests &gt; Paired Samples T-Test</strong>.</p>
<p>We will demonstrate using the dataset on the arthritis drug cross-over trial (<code>mod09_arthritis.csv</code>). Like the paired t-test the paired data need to be in separate columns.</p>
<p><img src="img/mod09/jamovi/mod09-wilcoxon-paired.png" class="img-fluid"></p>
</section>
<section id="estimating-rank-correlation-coefficients" class="level2" data-number="9.11">
<h2 data-number="9.11" class="anchored" data-anchor-id="estimating-rank-correlation-coefficients"><span class="header-section-number">9.11</span> Estimating rank correlation coefficients</h2>
<p>The analyses for Spearman’s and Kendall’s rank correlation are conducted in similar ways using <strong>Regression &gt; Correlation Matrix</strong>:</p>
<p><img src="img/mod09/jamovi/mod09-corr.png" class="img-fluid"></p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="r-notes" class="level1 unnumbered">
<h1 class="unnumbered">R notes</h1>
<section id="transforming-non-normally-distributed-variables-2" class="level2" data-number="9.12">
<h2 data-number="9.12" class="anchored" data-anchor-id="transforming-non-normally-distributed-variables-2"><span class="header-section-number">9.12</span> Transforming non-normally distributed variables</h2>
<p>One option for dealing with a non-normally distributed varaible is to transform it into its square, square root or logarithmic value. The new transformed variable may be normally distributed and therefore a parametric test can be used. First we check the distribution of the variable for normality, e.g.&nbsp;by plotting a histogram.</p>
<p>You can calculate a new, transformed, variable using standard commands. For example, to create a new column of data based on the log of length of stay:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jmv)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>hospital <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/examples/mod09_infection.rds"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>hospital<span class="sc">$</span>ln_los <span class="ot">&lt;-</span> <span class="fu">log</span>(hospital<span class="sc">$</span>los<span class="sc">+</span><span class="dv">1</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">descriptives</span>(<span class="at">data=</span>hospital, <span class="at">vars=</span><span class="fu">c</span>(los, ln_los))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 DESCRIPTIVES

 Descriptives                                    
 ─────────────────────────────────────────────── 
                         los         ln_los      
 ─────────────────────────────────────────────── 
   N                          132          132   
   Missing                      0            0   
   Mean                  38.05303     3.407232   
   Median                27.00000     3.332205   
   Standard deviation    35.78057    0.7149892   
   Minimum               0.000000     0.000000   
   Maximum               244.0000     5.501258   
 ─────────────────────────────────────────────── </code></pre>
</div>
</div>
<p>You can now check whether this logged variable is normally distributed as described in Module 2, for example by plotting a histogram as shown in Figure 9.2.</p>
<p>To obtain the back-transformed mean, we can use the <code>exp</code> command to <code>anti-log</code> the mean:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">3.407232</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 30.18159</code></pre>
</div>
</div>
<p>If your transformed variable is approximately normally distributed, you can apply parametric tests such as the t-test. In the Worked Example 9.1 dataset, the variable <code>infect</code> (presence of nosocomial infection) is a binary categorical variable. To test the hypothesis that patients with nosocomial infection have a different length of stay to patients without infection, you can conduct a t-test on the <code>ln_los</code> variable. You will need to back transform your mean values, as shown in Worked Example 9.1 in the course notes when reporting your results.</p>
</section>
<section id="wilcoxon-ranked-sum-test-1" class="level2" data-number="9.13">
<h2 data-number="9.13" class="anchored" data-anchor-id="wilcoxon-ranked-sum-test-1"><span class="header-section-number">9.13</span> Wilcoxon ranked-sum test</h2>
<p>We use the <code>wilcox.test</code> function to perform the Wilcoxon ranked-sum test:</p>
<pre><code>wilcox.test(continuous_variable ~ group_variable, data=df)</code></pre>
<p>Note that the implementation of R’s Wilcoxon rank-sum test uses a “continuity correction” for calculating the P-value from the ranks. This differs from Stata which does not use the continuity correction. While the use of the continuity correction is preferable, in most cases the difference in P-values between the methods will be minimal.</p>
<p>To obtain results that are consistent with Stata, the <code>correct=FALSE</code> option can be used:</p>
<pre><code>wilcox.test(continuous_variable ~ group_variable, data=df, correct=FALSE)</code></pre>
<p>The Wilcoxon ranked-sum test will be demonstrated using the length of stay data in <code>mod09_infection.rds</code>. Here, out continuous variable is <code>los</code> and the grouping variable is <code>infect</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(los <span class="sc">~</span> infect, <span class="at">data=</span>hospital)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  los by infect
W = 949, p-value = 0.01413
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
</section>
<section id="wilcoxon-matched-pairs-signed-rank-test-1" class="level2" data-number="9.14">
<h2 data-number="9.14" class="anchored" data-anchor-id="wilcoxon-matched-pairs-signed-rank-test-1"><span class="header-section-number">9.14</span> Wilcoxon matched-pairs signed-rank test</h2>
<p>The <code>wilcox.test</code> function can also be used to conduct the Wilcoxon matched-pairs signed-rank test. The specification of the variables is a little different, in that each variable is specified as <code>dataframe$variable</code>:</p>
<pre><code>wilcox.test(df$continuous_variable_1, df$continuous_variable_1, paired=TRUE)</code></pre>
<p>We will demonstrate using the dataset on the arthritis drug cross-over trial (<code>mod09_arthritis.csv</code>). Like the paired t-test the paired data need to be in separate columns.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>arthritis <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/examples/mod09_arthritis.csv"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(arthritis<span class="sc">$</span>drug_1, arthritis<span class="sc">$</span>drug_2, </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(arthritis$drug_1, arthritis$drug_2, paired =
TRUE): cannot compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  arthritis$drug_1 and arthritis$drug_2
V = 10.5, p-value = 0.04898
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
</section>
<section id="estimating-rank-correlation-coefficients-1" class="level2" data-number="9.15">
<h2 data-number="9.15" class="anchored" data-anchor-id="estimating-rank-correlation-coefficients-1"><span class="header-section-number">9.15</span> Estimating rank correlation coefficients</h2>
<p>The analyses for Spearman’s and Kendall’s rank correlation are conducted in similar ways:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>lung <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/examples/mod08_lung_function.csv"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(lung<span class="sc">$</span>Height, lung<span class="sc">$</span>FVC, <span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in cor.test.default(lung$Height, lung$FVC, method = "spearman"): Cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Spearman's rank correlation rho

data:  lung$Height and lung$FVC
S = 72796, p-value &lt; 2.2e-16
alternative hypothesis: true rho is not equal to 0
sample estimates:
      rho 
0.7472186 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(lung<span class="sc">$</span>Height, lung<span class="sc">$</span>FVC, <span class="at">method=</span><span class="st">"kendall"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kendall's rank correlation tau

data:  lung$Height and lung$FVC
z = 8.818, p-value &lt; 2.2e-16
alternative hypothesis: true tau is not equal to 0
sample estimates:
      tau 
0.5611396 </code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="activities" class="level1 unnumbered">
<h1 class="unnumbered">Activities</h1>
<section id="activity-9.1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-9.1">Activity 9.1</h3>
<p>There is a hypothesis that university students who live and dine in the university hall consume less vitamin C than the students who live and dine at home. To test the hypothesis, 30 students were randomly selected and their urinary ascorbic acid level was measured in mg over 3 hours. Urinary excretion of ascorbic acid is a measure of vitamin C nutrition in humans. The data is given in the following table and a copy of the data set, <code>Activity_9.1.csv</code> is also available on Moodle.</p>
<div class="cell">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-73f8a70e{}.cl-73f58f2e{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-73f712e0{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-73f71da8{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73f71db2{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-73f71db3{width:0.75in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-73f8a70e"><thead><tr style="overflow-wrap:break-word;"><th class="cl-73f71da8"><p class="cl-73f712e0"><span class="cl-73f58f2e">Living and dining in Hall (n.=.17)</span></p></th><th class="cl-73f71da8"><p class="cl-73f712e0"><span class="cl-73f58f2e">Living and dining at Home (n = 13)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">34</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">163</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">62</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">205</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">37</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">83</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">27</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">372</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">38</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">50</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">20</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">22</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">7</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">47</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">53</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">255</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">22</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">30</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">37</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">89</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">14</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">96</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">28</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">48</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">28</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">25</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">70</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">163</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">16</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e">9</span></p></td><td class="cl-73f71db2"><p class="cl-73f712e0"><span class="cl-73f58f2e"></span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-73f71db3"><p class="cl-73f712e0"><span class="cl-73f58f2e">121</span></p></td><td class="cl-73f71db3"><p class="cl-73f712e0"><span class="cl-73f58f2e"></span></p></td></tr></tbody></table></div>
</div>
</div>
<ol type="a">
<li>Examine the distribution of the data using a box-plot and histogram, and obtain descriptive statistics. How would you describe the distribution of ascorbic acid?</li>
<li>Which statistical test would be appropriate to test the hypothesis mentioned in the question and why?</li>
<li>State the hypotheses appropriate to the analytical method you mentioned in (b).</li>
<li>Carry out the statistical test you have mentioned in (b) and write your conclusion.</li>
</ol>
</section>
<section id="activity-9.2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-9.2">Activity 9.2</h3>
<p>A drug was tested for its effect in lowering blood pressure. Fifteen women with hypertension were enrolled and had their systolic blood pressure measured before and after taking the drug. The data are available in the file <code>Activity_9.2.csv</code> on Moodle.</p>
<ol type="a">
<li>State the research question and the null hypothesis.</li>
<li>Obtain suitable summary statistics and test the null hypothesis. Describe the reason for choosing the test.</li>
<li>Write a brief conclusion.</li>
<li>What are the main limitations of this study? Consider both epidemiological and statistical aspects.</li>
</ol>
</section>
<section id="activity-9.3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="activity-9.3">Activity 9.3</h3>
<p>It is often necessary to take blood from newborn babies, which causes them pain. A group of researchers wanted to test whether a pacifier (dummy) would provide some pain relief. Newborn babies undergoing venepuncture were randomised to one of two treatment groups. In the placebo group, babies had blood taken as per the usual protocol. In the pacifier group, babies were allowed to suck on a pacifier while having their blood taken. Each venepuncture was observed by an assessor, who rated the baby’s pain on the DAN scale which ranges from 0 (no pain) to 10. The DAN is based on observation of the baby’s facial expression, limb movement, and vocal expression. The data are provided in the file <code>Activity_9.3.csv</code>.</p>
<p>Analyse these data to answer the research question. Write a brief report summarising your results and state your conclusion.</p>
</section>
<section id="supplementary-activity-9.4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="supplementary-activity-9.4">Supplementary Activity 9.4</h3>
<p>A study was conducted among 201 people who had recently quit smoking. The dataset Activity_9.4_smoke.csv contains the following variables:</p>
<ul>
<li>ID: participant ID number</li>
<li>age: participant age (years)</li>
<li>gender: participant gender (1=Male, 2=Female)</li>
<li>day_abs: number of days abstinent (i.e., number of days since last cigarette)</li>
</ul>
<p>Analyse these data to assess whether there is a difference in the number of days abstinent between males and females. Write a brief report summarising your results and state your conclusion.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-bland15" class="csl-entry" role="listitem">
Bland, Martin. 2015. <em>An <span>Introduction</span> to <span>Medical Statistics</span></em>. 4th Edition. Oxford, New York: Oxford University Press.
</div>
<div id="ref-kirkwood_sterne01" class="csl-entry" role="listitem">
Kirkwood, Betty, and Jonathan Sterne. 2001. <em>Essentials of <span>Medical Statistics</span></em>. 2nd edition. Malden, Mass: Wiley-Blackwell.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./08-correlation-and-regression.html" class="pagination-link" aria-label="Correlation and simple linear regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./98.1-appendix1.html" class="pagination-link" aria-label="Appendix">
        <span class="nav-page-text">Appendix</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>